# Generated by Django 4.2.3 on 2023-08-19 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=200)),
                ('palabras_clave', models.CharField(max_length=200)),
                ('facultad', models.CharField(max_length=100)),
                ('programa', models.CharField(max_length=100)),
                ('grupo_investigacion', models.CharField(max_length=200)),
                ('linea_investigacion', models.CharField(max_length=200)),
                ('semillero_investigacion', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=300)),
                ('correo', models.EmailField(max_length=100)),
                ('cvlac', models.URLField(blank=True)),
                ('co_investigador_1_nombre', models.CharField(blank=True, max_length=100)),
                ('co_investigador_1_identificacion', models.CharField(blank=True, max_length=20)),
                ('co_investigador_1_telefono', models.CharField(blank=True, max_length=300)),
                ('co_investigador_1_correo', models.EmailField(blank=True, max_length=100)),
                ('co_investigador_1_formacion', models.CharField(blank=True, max_length=100)),
                ('co_investigador_1_institucion', models.CharField(blank=True, max_length=200)),
                ('co_investigador_1_cvlac', models.URLField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True)),
                ('fecha_finalizacion', models.DateField(blank=True)),
                ('problema_pregunta', models.TextField(blank=True)),
                ('justificacion', models.TextField(blank=True)),
                ('objetivo_general', models.TextField(blank=True)),
                ('objetivos_especificos', models.TextField(blank=True)),
                ('metodologia_propuesta', models.TextField(blank=True)),
                ('estado_arte', models.TextField(blank=True)),
                ('impactos_esperados', models.TextField(blank=True)),
                ('comite_etica', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='Adjuntos_Comite_Etica/')),
                ('aprobado', models.BooleanField(default=False)),
                ('aprobado_nombre', models.CharField(max_length=100)),
                ('aprobado_fecha', models.DateField(auto_now_add=True)),
                ('aprobado_adjunto', models.FileField(blank=True, null=True, upload_to='Adjuntos_aprobado/')),
                ('porcentaje_cumplimiento_total', models.FloatField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Generación de Nuevo Conocimiento', 'Generación de Nuevo Conocimiento'), ('Desarrollo Tecnológico e Innovación', 'Desarrollo Tecnológico e Innovación'), ('Apropiación Social del Conocimiento', 'Apropiación Social del Conocimiento'), ('Formación del Recurso Humano CteI', 'Formación del Recurso Humano CteI'), ('Gestión de semillero', 'Gestión de semillero'), ('Otros encargos', 'Otros encargos')], max_length=300)),
                ('tipo_producto', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField(default=1)),
                ('estado_0', models.CharField(default='No Iniciado', max_length=300)),
                ('estado_0_justificado', models.CharField(default='', max_length=300)),
                ('estado_1', models.CharField(default='', max_length=300)),
                ('estado_2', models.CharField(default='', max_length=300)),
                ('estado_3', models.CharField(default='', max_length=300)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avance_0_justificacion', models.TextField()),
                ('avance_0_fecha', models.DateField(blank=True, null=True)),
                ('avance_1_nombre', models.CharField(max_length=300)),
                ('avance_1_descripcion', models.TextField(max_length=500)),
                ('avance_1_link', models.URLField(blank=True, max_length=300)),
                ('avance_1_adjunto', models.FileField(blank=True, null=True, upload_to='Adjuntos_avance/')),
                ('avance_1_fecha', models.DateField(blank=True, null=True)),
                ('avance_1_estado', models.CharField(default='No Revisado', max_length=300)),
                ('avance_1_observacion', models.CharField(max_length=300)),
                ('avance_1_correcciones_realizadas', models.BooleanField(default=False)),
                ('porcentaje_avance_1', models.FloatField(default=0)),
                ('avance_2_descripcion', models.TextField(max_length=500)),
                ('avance_2_link', models.URLField(blank=True, max_length=300)),
                ('avance_2_adjunto', models.FileField(blank=True, null=True, upload_to='Adjuntos_avance/')),
                ('avance_2_fecha', models.DateField(blank=True, null=True)),
                ('avance_2_estado', models.CharField(default='No Revisado', max_length=300)),
                ('avance_2_observacion', models.CharField(max_length=300)),
                ('avance_2_correcciones_realizadas', models.BooleanField(default=False)),
                ('porcentaje_avance_2', models.FloatField(default=0)),
                ('avance_3_descripcion', models.TextField(max_length=500)),
                ('avance_3_link', models.URLField(blank=True, max_length=300)),
                ('avance_3_adjunto', models.FileField(blank=True, null=True, upload_to='Adjuntos_avance/')),
                ('avance_3_fecha', models.DateField(blank=True, null=True)),
                ('avance_3_estado', models.CharField(default='No Revisado', max_length=300)),
                ('avance_3_observacion', models.CharField(max_length=300)),
                ('avance_3_correcciones_realizadas', models.BooleanField(default=False)),
                ('porcentaje_avance_3', models.FloatField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.producto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion', models.IntegerField()),
                ('tipo_duracion', models.CharField(choices=[('semanas', 'Fecha de Semanas'), ('meses', 'Fecha por Meses')], max_length=10)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='Proyectos.proyecto')),
            ],
        ),
    ]
