# Generated by Django 4.2.3 on 2023-11-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(help_text='Descripcion de los estados de los productos', max_length=200, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'EstadoProducto',
                'verbose_name_plural': 'EstadoProductos',
            },
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='avance_2_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos_avance/'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='avance_3_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos_avance/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='aprobado_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos_aprobado/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos_comite_etica/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Proyectos.estadoproducto'),
        ),
    ]
