# Generated by Django 4.2.3 on 2023-08-19 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LineaInvestigacion_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LineaInvestigacion_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('es_administrador', models.BooleanField(default=True)),
                ('cargo', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, related_name='administradores', to='auth.group', verbose_name='grupos')),
                ('user_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_administrador', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='administradores', to='auth.permission', verbose_name='permisos de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('cvlac', models.URLField(blank=True)),
                ('orcid', models.URLField(blank=True)),
                ('google_scholar', models.URLField(blank=True)),
                ('categoria', models.CharField(choices=[('Junior', 'Junior'), ('Asociado', 'Asociado'), ('Emerito', 'Emerito'), ('No_Reconocido', 'No_Reconocido')], default='No_Reconocido', max_length=100)),
                ('facultad', models.CharField(blank=True, choices=[('Humanidades', 'Humanidades'), ('Ciencias_Admin', 'Ciencias_Admin'), ('Ingenieria', 'Ingenieria'), ('Educacion', 'Educacion')], max_length=200)),
                ('Programa', models.CharField(blank=True, max_length=100)),
                ('grupo_investigacion', models.CharField(blank=True, choices=[('Aglalia', 'Aglalia'), ('ProCont', 'ProCont'), ('DehJüs', 'DehJüs'), ('TES', 'TES'), ('GECAES', 'GECAES'), ('Gestion e Innovacion', 'Gestion e Innovacion'), ('IC', 'IC'), ('LyS', 'LyS'), ('Gisela', 'Gisela'), ('LAW', 'LAW'), ('Business Intelligence', 'Business Intelligence'), ('Americana Emprendedora', 'Americana Emprendedora'), ('PSI Context', 'PSI Context'), ('Engineeri', 'Engineeri'), ('SeHaT', 'SeHaT')], max_length=200, null=True)),
                ('grupo_investigacion_2', models.CharField(blank=True, choices=[('Aglalia', 'Aglalia'), ('ProCont', 'ProCont'), ('DehJüs', 'DehJüs'), ('TES', 'TES'), ('GECAES', 'GECAES'), ('Gestion e Innovacion', 'Gestion e Innovacion'), ('IC', 'IC'), ('LyS', 'LyS'), ('Gisela', 'Gisela'), ('LAW', 'LAW'), ('Business Intelligence', 'Business Intelligence'), ('Americana Emprendedora', 'Americana Emprendedora'), ('PSI Context', 'PSI Context'), ('Engineeri', 'Engineeri'), ('SeHaT', 'SeHaT')], max_length=200, null=True)),
                ('grupo_investigacion_3', models.CharField(blank=True, choices=[('Aglalia', 'Aglalia'), ('ProCont', 'ProCont'), ('DehJüs', 'DehJüs'), ('TES', 'TES'), ('GECAES', 'GECAES'), ('Gestion e Innovacion', 'Gestion e Innovacion'), ('IC', 'IC'), ('LyS', 'LyS'), ('Gisela', 'Gisela'), ('LAW', 'LAW'), ('Business Intelligence', 'Business Intelligence'), ('Americana Emprendedora', 'Americana Emprendedora'), ('PSI Context', 'PSI Context'), ('Engineeri', 'Engineeri'), ('SeHaT', 'SeHaT')], max_length=200, null=True)),
                ('lineas_investigacion', models.ManyToManyField(blank=True, to='Users.lineainvestigacion')),
                ('lineas_investigacion_2', models.ManyToManyField(blank=True, to='Users.lineainvestigacion_2')),
                ('lineas_investigacion_3', models.ManyToManyField(blank=True, to='Users.lineainvestigacion_3')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
