# Generated by Django 4.2.3 on 2023-08-23 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('programa', models.CharField(blank=True, max_length=100)),
                ('user_e', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
