# Generated by Django 4.2.3 on 2023-08-23 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semillero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('facultad', models.CharField(max_length=100)),
                ('programa', models.CharField(max_length=100)),
                ('grupo_investigacion', models.CharField(max_length=200)),
                ('linea_investigacion', models.CharField(max_length=200)),
                ('tematica_estudio', models.CharField(max_length=200)),
                ('justificacion_semillero', models.CharField(max_length=500)),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=300)),
                ('correo', models.EmailField(max_length=100)),
                ('cvlac', models.URLField(blank=True)),
                ('nivel_ingles_habla', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=300)),
                ('nivel_ingles_lee', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=300)),
                ('nivel_ingles_entiende', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=300)),
                ('nivel_ingles_escribe', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=300)),
                ('docente_investigador', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
                ('tematica', models.CharField(blank=True, max_length=200)),
                ('institucion', models.CharField(blank=True, max_length=200)),
                ('horas', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
