# Generated by Django 4.2.3 on 2023-08-31 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Semilleros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='user_e',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.usuario_estudiante'),
        ),
        migrations.AddField(
            model_name='actividadessemillero',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Semilleros.inscripcionsemillero'),
        ),
        migrations.AddField(
            model_name='actividadessemillero',
            name='semillero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Semilleros.semillero'),
        ),
        migrations.AddField(
            model_name='actividadessemillero',
            name='user_e',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.usuario_estudiante'),
        ),
    ]
