# Generated by Django 4.2.3 on 2023-08-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0002_semillero_nombre_semillero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='nivel_formacion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
