# Generated by Django 4.2.3 on 2023-08-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0003_remove_inscripcionsemillero_proyecto_interes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcionsemillero',
            old_name='semillero_interes',
            new_name='semillero_proyecto_interes',
        ),
    ]
