# Generated by Django 4.2.3 on 2023-08-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0003_semillero_nivel_formacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semillero',
            name='docente_investigador',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=2),
        ),
        migrations.AlterField(
            model_name='semillero',
            name='fecha',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
