# Generated by Django 4.2.3 on 2023-08-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0004_rename_semillero_interes_inscripcionsemillero_semillero_proyecto_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='proyecto_interes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
