# Generated by Django 4.2.3 on 2023-08-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0004_alter_semillero_docente_investigador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='fecha_2',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='semillero',
            name='fecha_3',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='semillero',
            name='horas_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='horas_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='institucion_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='institucion_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='tematica_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='tematica_3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
