# Generated by Django 4.2.3 on 2023-08-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0005_semillero_fecha_2_semillero_fecha_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='tiene_cvlac',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2),
        ),
    ]
