# Generated by Django 4.2.3 on 2023-08-31 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0001_initial'),
        ('Semilleros', '0005_inscripcionsemillero_proyecto_interes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionsemillero',
            name='proyecto_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Proyectos.proyecto'),
        ),
    ]
