# Generated by Django 4.2.3 on 2023-08-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0001_initial'),
        ('Semilleros', '0006_semillero_tiene_cvlac'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='proyectos',
            field=models.ManyToManyField(blank=True, to='Proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='semillero',
            name='tiene_proyectos',
            field=models.CharField(choices=[('no', 'No'), ('si', 'Sí')], default='no', max_length=2),
        ),
    ]
