# Generated by Django 4.2.3 on 2023-08-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0007_semillero_proyectos_semillero_tiene_proyectos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades_Inter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo_comite', models.CharField(max_length=100)),
                ('actividad_tema', models.CharField(max_length=100)),
                ('tipo_vinculacion', models.CharField(max_length=100)),
                ('fecha', models.DateField(blank=True)),
                ('semillero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Semilleros.semillero')),
            ],
        ),
    ]
