# Generated by Django 4.2.3 on 2023-08-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0008_actividades_inter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades_inter',
            name='semillero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='Semilleros.semillero'),
        ),
    ]
