# Generated by Django 4.2.3 on 2023-08-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0009_alter_actividades_inter_semillero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actividades_Inter',
        ),
    ]
