# Generated by Django 4.2.3 on 2023-08-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0010_delete_actividades_inter'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='actividad_tema',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='actividades',
            field=models.CharField(choices=[('no', 'No'), ('si', 'Sí')], default='no', max_length=2),
        ),
        migrations.AddField(
            model_name='semillero',
            name='fecha_actividad',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='semillero',
            name='nombre_grupo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='tipo_vinculacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
