# Generated by Django 4.2.3 on 2023-08-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0011_semillero_actividad_tema_semillero_actividades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='actividad_tema_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='actividad_tema_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='fecha_actividad_2',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='semillero',
            name='fecha_actividad_3',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='semillero',
            name='nombre_grupo_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='nombre_grupo_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='tipo_vinculacion_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='tipo_vinculacion_3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
