# Generated by Django 4.2.3 on 2023-08-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0012_semillero_actividad_tema_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='Se_fehca',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='semillero',
            name='Se_fehca_2',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='semillero',
            name='Se_fehca_3',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='semillero',
            name='Se_institucion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='Se_institucion_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='Se_institucion_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='Se_nombre_proyecto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='Se_nombre_proyecto_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='Se_nombre_proyecto_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='Se_tipo_vinculacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='Se_tipo_vinculacion_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semillero',
            name='Se_tipo_vinculacion_3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
