# Generated by Django 4.2.3 on 2023-08-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0013_semillero_se_fehca_semillero_se_fehca_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semillero',
            old_name='Se_fehca',
            new_name='Se_fecha',
        ),
        migrations.RenameField(
            model_name='semillero',
            old_name='Se_fehca_2',
            new_name='Se_fecha_2',
        ),
        migrations.RenameField(
            model_name='semillero',
            old_name='Se_fehca_3',
            new_name='Se_fecha_3',
        ),
    ]
