# Generated by Django 4.2.3 on 2023-08-25 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_usuario_estudiante'),
        ('Semilleros', '0014_rename_se_fehca_semillero_se_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionSemillero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_e', models.CharField(max_length=100)),
                ('identificacion_e', models.CharField(max_length=20, unique=True)),
                ('telefono_e', models.CharField(max_length=20)),
                ('correo_e', models.EmailField(max_length=100)),
                ('clave_e', models.CharField(max_length=100)),
                ('programa_e', models.CharField(blank=True, max_length=100)),
                ('fecha_inscripcion_e', models.DateTimeField(auto_now_add=True)),
                ('estado_e', models.BooleanField(default=False)),
                ('semillero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Semilleros.semillero')),
                ('user_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.usuario_estudiante')),
            ],
        ),
    ]
