# Generated by Django 4.2.3 on 2023-08-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0016_remove_inscripcionsemillero_clave_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionsemillero',
            name='identificacion_e',
            field=models.CharField(max_length=20),
        ),
    ]
