# Generated by Django 4.2.3 on 2023-08-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0017_alter_inscripcionsemillero_identificacion_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='tipo_solicitante',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('egresado', 'Egresado'), ('otro', 'Otro (indique cual)')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
