# Generated by Django 4.2.3 on 2023-08-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0019_inscripcionsemillero_semillero_inscrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='tipo_solicitante_otro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
