# Generated by Django 4.2.3 on 2023-08-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0020_inscripcionsemillero_tipo_solicitante_otro'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='nivel_ingles_entiende_e',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='nivel_ingles_escribe_e',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='nivel_ingles_habla_e',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='nivel_ingles_lee_e',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default=1, max_length=300),
            preserve_default=False,
        ),
    ]
