# Generated by Django 4.2.3 on 2023-08-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0021_inscripcionsemillero_nivel_ingles_entiende_e_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='año_ingreso',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='cursos_inves',
            field=models.CharField(choices=[('no', 'No'), ('si', 'Sí')], default='no', max_length=2),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='fecha_e',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='fecha_e_2',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='fecha_grado',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='horas_e',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='horas_e_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='institucion_e',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='institucion_e_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='semestre_actual',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='tematica_e',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='tematica_e_2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
