# Generated by Django 4.2.3 on 2023-08-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0022_inscripcionsemillero_año_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionsemillero',
            name='horas_e',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='inscripcionsemillero',
            name='institucion_e_2',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
