# Generated by Django 4.2.3 on 2023-08-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0023_alter_inscripcionsemillero_horas_e_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='cvlac_e',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='tiene_cvlac_e',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2),
        ),
    ]
