# Generated by Django 4.2.3 on 2023-08-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0001_initial'),
        ('Semilleros', '0024_inscripcionsemillero_cvlac_e_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='Se_fecha_e',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='Se_fecha_e_2',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='Se_fecha_e_3',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='Se_institucion_e',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='Se_institucion_e_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='Se_institucion_e_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='Se_nombre_proyecto_e',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='Se_nombre_proyecto_e_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='Se_nombre_proyecto_e_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='Se_tipo_vinculacion_e',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='Se_tipo_vinculacion_e_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='Se_tipo_vinculacion_e_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='participa_proyectos',
            field=models.CharField(choices=[('no', 'No'), ('si', 'Sí')], default='no', max_length=2),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='proyectos',
            field=models.ManyToManyField(blank=True, to='Proyectos.proyecto'),
        ),
    ]
