# Generated by Django 4.2.3 on 2023-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0025_inscripcionsemillero_se_fecha_e_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='actividad_tema_e',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='actividad_tema_e_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='actividades_e',
            field=models.CharField(choices=[('no', 'No'), ('si', 'Sí')], default='no', max_length=2),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='fecha_actividad_e',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='fecha_actividad_e_2',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='nombre_grupo_e',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='nombre_grupo_e_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='tipo_vinculacion_e',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='tipo_vinculacion_e_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inscripcionsemillero',
            name='semillero_inscrito',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
