# Generated by Django 4.2.3 on 2023-08-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0026_inscripcionsemillero_actividad_tema_e_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcionsemillero',
            old_name='semillero_inscrito',
            new_name='semillero_proyecto_interes',
        ),
    ]
