# Generated by Django 4.2.3 on 2023-08-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0027_rename_semillero_inscrito_inscripcionsemillero_semillero_proyecto_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='linea_sublinea',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
