# Generated by Django 4.2.3 on 2023-08-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0028_inscripcionsemillero_linea_sublinea'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='horas_semanales',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='tipo_semillero',
            field=models.CharField(choices=[('--', '--'), ('unica', 'Fase Unica'), ('doble', 'Fase Doble'), ('triple', 'Fase Triple')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
