# Generated by Django 4.2.3 on 2023-08-28 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0029_inscripcionsemillero_horas_semanales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionsemillero',
            name='horas_semanales',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40)]),
        ),
    ]
