# Generated by Django 4.2.3 on 2023-08-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0034_semillero_direccion_semillero_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='direccion_e',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='fecha_nacimiento_e',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='lugar_expedicion_e',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcionsemillero',
            name='lugar_nacimiento_e',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
