# Generated by Django 4.2.3 on 2023-08-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_usuario_estudiante'),
        ('Semilleros', '0036_alter_inscripcionsemillero_horas_e_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesSemillero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Semilleros.inscripcionsemillero')),
                ('semillero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Semilleros.semillero')),
                ('user_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.usuario_estudiante')),
            ],
        ),
    ]
