# Generated by Django 4.2.3 on 2023-08-30 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0037_actividadessemillero'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadessemillero',
            name='ciudad_actividad_e',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='actividadessemillero',
            name='descripcion_actividad_e',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='actividadessemillero',
            name='fecha_actividad_final_e',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='actividadessemillero',
            name='fecha_actividad_inicio_e',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='actividadessemillero',
            name='identificacion_estuidante_actividad_e',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividadessemillero',
            name='lugar_actividad_e',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='actividadessemillero',
            name='nombre_actividad_e',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='actividadessemillero',
            name='nombre_estuidante_actividad_e',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividadessemillero',
            name='participantes_actividad_e',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
