# Generated by Django 4.2.3 on 2023-08-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semilleros', '0038_actividadessemillero_ciudad_actividad_e_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadessemillero',
            name='adjunto_actividad_e',
            field=models.FileField(blank=True, null=True, upload_to='Adjuntos_Actividades_E/'),
        ),
    ]
